### ISSUE TITLE
sqlite build error 

### ISSUE THREAD

**Issue by YYxDeveloper** [enginebai/Movie-lol-android#78]
新手指教
**Describe the bug**
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at androidx.room.verifier.DatabaseVerifier.<clinit>(DatabaseVerifier.kt:71)
	... 50 more

**Comment by YYxDeveloper** [comment]
查出的資訊似乎是跟m1有衝突，但不知道該怎麼修

**Comment by enginebai** [comment]
It seems to be Room bug on Mac M1. Can you try to fix this on your Mac to upgrade Room verions to `2.4.0` and above since I don't have Mac machine with M1 chip. If this can be fixed by upgrading the Room version, feel free to submit PR. That would be nice :)

Source: https://stackoverflow.com/a/69142381/2279285

**Comment by enginebai** [comment]
Hi, did you fix this issue from the link I provided above?

**Comment by enginebai** [comment]
I will close this issue since there is no further update information, feel free to re-open if you still have some problem.

**Comment by YYxDeveloper** [comment]
yes,it's fixed thank you
